core/urls.py
from django.urls import path, include

from .views import (
    home,
    lista_pessoas,
    lista_veiculos,
    lista_movrotativos,
    lista_mensalistas,
    lista_movmensalistas,
    pessoa_novo,
    veiculo_novo,
    movrotativos_novo,
    mensalista_novo,
    movmensalista_novo,
    pessoa_update,
    veiculo_update,
    movrotativos_update,
    mensalista_update,
    movmensalista_update,
    pessoa_delete,
    veiculo_delete,
    movrotativos_delete,
    mensalista_delete,
    movmensalista_delete,
    logout_user,
    )


app_name = "core"
urlpatterns = [
    path("", home, name="core_home"),
    path("pessoas/", lista_pessoas, name="core_lista_pessoas"),
    path("pessoa-novo/", pessoa_novo, name="core_pessoa_novo"),
    path("pessoa-update/<int:id>/", pessoa_update, name="core_pessoa_update"),
    path("pessoa-delete/<int:id>/", pessoa_delete, name="core_pessoa_delete"),

    path("veiculos/", lista_veiculos, name="core_lista_veiculos"),
    path("veiculo-novo/", veiculo_novo, name="core_veiculo_novo"),
    path("veiculo-update/<int:id>/", veiculo_update, name="core_veiculo_update"),
    path("veiculo-delete/<int:id>/", veiculo_delete, name="core_veiculo_delete"),

    path("mov-rot/", lista_movrotativos, name="core_lista_movrotativos"),
    path("mov-rot-novo/", movrotativos_novo, name="core_movrotativos_novo"),
    path("mov-rot-update/<int:id>/", movrotativos_update,
         name="core_movrotativos_update"),
    path("mov-rot-delete/<int:id>/", movrotativos_delete,
         name="core_movrotativos_delete"),

    path("mensalistas/", lista_mensalistas, name="core_lista_mensalistas"),
    path("mensalista-novo/", mensalista_novo, name="core_mensalista_novo"),
    path("mensalista-update/<int:id>/", mensalista_update,
         name="core_mensalista_update"),
    path("mensalista-delete/<int:id>/", mensalista_delete,
         name="core_mensalista_delete"),

    path("mov-mensal/", lista_movmensalistas,
         name="core_lista_movmensalistas"),
    path("mov-mensal-novo/", movmensalista_novo,
         name="core_movmensalista_novo"),
    path("movmensal-update/<int:id>/", movmensalista_update,
         name="core_movmensalista_update"),
    path("mov-mensal-delete/<int:id>/", movmensalista_delete,
         name="core_movmensalista_delete"),

    path("logout/", logout_user, name="logout"),
]

estacionamento/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('website.urls')),
    path("sistema/", include("core.urls")),
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
]

website/urls.py
from django.urls import path
from .views import home, contato, servicos, sobre, planos


app_name = "website"
urlpatterns = [
    path("", home, name="website_home"),
    path("contato/", contato, name="website_contato"),
    path("servicos/", servicos, name="website_servicos"),
    path("sobre/", sobre, name="website_sobre"),
    path("planos/", planos, name="website_planos"),
]

website/models.py
from django.db import models


class Contato(models.Model):
    nome = models.CharField(max_length=100)
    email = models.EmailField()
    telefone = models.CharField(max_length=20)
    mensagem = models.TextField()

    def __str__(self):
        return self.nome

website/views.py
from django.shortcuts import render
from .models import Contato


def home(request):
    return render(request, "website/index.html")


def contato(request):
    mensagem = ""
    if request.method == "POST":
        try:
            contato = {}
            contato["nome"] = request.POST.get("nome")
            contato["email"] = request.POST.get("email")
            contato["telefone"] = request.POST.get("telefone")
            contato["mensagem"] = request.POST.get("mensagem")

            Contato.objects.create(**contato)
        except Exception as e:
            mensagem = str(e)
        else:
            mensagem = "contato realizado com sucesso"
    return render(request, "website/contato.html", {"mensagem": mensagem})


def servicos(request):
    return render(request, "website/servicos.html")


def sobre(request):
    return render(request, "website/sobre.html")


def planos(request):
    return render(request, "website/planos.html")

website/templates/website/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'website/css/style.css' %}">
    <title>Website - Estacionamento</title>
</head>
<body>    
    <div class="container">
        <div class="row">
            <div class="col-6">
                <h1>Estacionamento 24 Horas</h1>
                <span>Security in first time</span>
            </div>
            <div class="col-6 img-right">
                <img src="{% static 'img/logo.png' %}" alt="Estacionamento 24 horas">
            </div>
        </div>

        {% include "website/menu.html" %}

        {% block main %}
        {% endblock main %}

        {% include "website/footer.html" %}
        
    </div>
</body>
</html>

website/templates/website/contato.html
{% extends "website/base.html" %}
{% load static %}

{% block main %}
    <div class="row">
        <p> {{ mensagem }} </p>
    </div>
    <div class="row row-space">
        <p>Fale conosco</p>        
        <div class="col-5">
            <form class="row g-3" method="POST">
                {% csrf_token %}
                <div class="col-12 form-row">                    
                    <input type="text" class="form-control" id="inputNome" placeholder="Digite seu nome" name="nome">
                </div>
                <div class="col-md-6 form-row">
                    <label for="inputEmail4" class="form-label">Email</label>
                    <input type="email" class="form-control" id="inputEmail4" name="email">
                </div>
                <div class="col-md-6 form-row">
                    <label for="inputTelefone" class="form-label">Telefone</label>
                    <input type="text" class="form-control" id="inputTelefone" name="telefone">
                </div>                
                <div class="mb-3 form-row">                    
                    <textarea class="form-control" id="" rows="10" name="mensagem"></textarea>
                </div>
                <div class="col-12">
                    <button type="submit" class="btn btn-primary">Enviar</button>
                </div>                
            </form>
        </div>

        <div class="col-7">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expli
              cabo, accusamus enim maiores atque ullam labore tenetur. Odit s
              uscipit est soluta, eum tempore excepturi inventore neque delen
              iti nihil dolore. Iure, dolores?Lorem ipsum dolor sit amet cons
              ectetur adipisicing elit. Inventore ea porro voluptates odio, a
              spernatur id enim, molestias libero quaerat doloribus adipisci 
              dolorum nam fugiat? Error odit ducimus inventore ab eius?
            </p>
            <div class="">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3750.142940571672!2d-44.14048892385548!3d-19.960490039260485!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xa6c3e08e8c597b%3A0x8ab5ada8f75cc390!2sCentro%20de%20Forma%C3%A7%C3%A3o%20de%20Condutores%20petropolis!5e0!3m2!1spt-BR!2sbr!4v1718159126876!5m2!1spt-BR!2sbr" width="100%" height="300" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe> 
            </div>       
        </div>
    </div>    

{% endblock main %}

website/templates/website/footer.html
{% load static %}

<div class="row row-space">
    <div class="col-3">
        <nav class="nav flex-column">
            <a class="nav-link active" aria-current="page" href="{% url 'website:website_home' %}">Home</a>
            <a class="nav-link" href="{% url 'website:website_servicos' %}">Servicos</a>
            <a class="nav-link" href="{% url 'website:website_planos' %}">Planos</a>
            <a class="nav-link" href="{% url 'website:website_contato' %}">Contato</a>
          </nav>
    </div>
    <div class="col-6">   
        <p class="footer-website">
            Copyright - Todos os direitos reservados | Desenvolvido por Teodoro Tec
        </p>
    </div>
    <div class="col-3"></div>
</div>

website/templates/website/index.html
{% extends "website/base.html" %}
{% load static %}

{% block main %}
    <div class="row row-space">
        <div class="col-6">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Est
            facere fuga dolore ut accusantium totam laudantium ipsa susc
            ipit nobis fugiat repellat at voluptatem tempora, quo, cupid
            itate, corrupti repellendus sed et.
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. De
            lectus magni aperiam autem sequi incidunt obcaecati dicta en
            im, pariatur earum odit libero voluptatum nulla error harum 
            totam nemo quaerat, minima quod!
        </div>
        <div class="col-6">
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Co
            mmodi explicabo non totam modi? Dolorem dolor mollitia imped
            it necessitatibus, est totam at eaque quod voluptatum conseq
            uuntur temporibus laboriosam officiis perspiciatis consequat
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Tem
            poribus est quibusdam ipsa. Est aliquid voluptas sint recusa
            ndae nobis accusantium quo numquam voluptate. Nemo ducimus e
            um quisquam maiores voluptates dolorum laborum?
        </div>
    </div>

    <div class="row row-space">
        <div class="col-4">
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ear
            um totam excepturi cupiditate atque assumenda architecto sit 
            ratione mollitia temporibus optio illo dicta fugiat blanditi
            is porro, magni, deserunt repellat veniam odio?
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qua
            m nihil eum libero nisi non quasi soluta at error tempore, pr
            aesentium molestias odit alias delectus. Debitis soluta ipsum
             vero explicabo praesentium?
        </div>

        <div class="col-4 img-website">
            <img src="{% static 'img/parking.png' %}" alt="Estacionamento 24 horas">
        </div>

        <div class="col-4">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa
             odio, blanditiis beatae saepe quasi quaerat suscipit. Animi f
             ugit, iste odit sequi, modi, aperiam adipisci vero inventore 
             repellat sed rem consequatur?
            Lorem ipsum dolor sit amet consectetur adipisicing elit. A nem
            o quam soluta doloribus minima neque at natus nostrum culpa? A
            spernatur reprehenderit, nisi impedit sequi facilis fugiat ut 
            maiores? Nihil, tenetur?
        </div>
    </div>

    <div class="row row-space">
        <div class="col-6">
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Itaque
             rem nostrum ea modi in ab dolorem, soluta cupiditate. Rerum, p
             laceat sit. Adipisci, aperiam nam provident consequuntur minus 
             mollitia nesciunt sint!
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Vero,
             dolor debitis accusantium architecto necessitatibus adipisci p
             rovident, rem nisi sint eaque reiciendis sapiente, ducimus off
             icia atque ut. Eos delectus a minus.
        </div>
        <div class="col-6">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa h
            arum similique impedit modi nisi fugit beatae! Aspernatur magni
             quae sunt commodi quos eum a nihil! Et at nemo tempore blandit
             iis!
        </div>
    </div>    
{% endblock main %}

website/templates/website/menu.html
<div class="row row-space">
    <div class=col-12>
        <ul class="nav bar nav-fill">
            <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'website:website_home' %}">Home</a>
            </li>  
            <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'website:website_servicos' %}">Servicos</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'website:website_sobre' %}">Sobre</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'website:website_planos' %}">Planos</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'website:website_contato' %}">Contato</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'core:core_home' %}">Sistema</a>
            </li>
        </ul>
    </div>    
</div>

website/templates/website/planos.html
{% extends "website/base.html" %}
{% load static %}

{% block main %}
    <div class="row row-space">
        <div class="col-8">
            <p>
                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Id of
                ficia eius iusto eos labore fuga similique reprehenderit! Ducim
                us voluptatum, quisquam facere cumque, quasi id doloremque repu
                diandae incidunt eum porro sint!
                Lorem ipsum dolor sit amet consectetur, adipisicing elit. Facil
                is, quo. Quibusdam repudiandae, at quasi odit sint incidunt ali
                quam eum veniam! Laudantium saepe hic ipsum nesciunt nam ex in 
                id odio.
            </p>
            <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad sint
                sit dolore exercitationem vero totam maiores ipsa cumque asperi
                ores quibusdam ipsam facere deserunt quos at nihil blanditiis h
                arum, debitis incidunt!
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere,
                praesentium? Harum accusantium cum aliquid dolores perspiciatis,
                minus laboriosam veritatis accusamus ut dolor quidem minima, et
                impedit natus repudiandae. Voluptatum, porro.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Optio b
                eatae nemo sit quae tempora dolorum debitis? Voluptate ea ipsa, 
                obcaecati atque quasi accusamus accusantium laboriosam? Optio mag
                nam ex eaque facere.
            </p>            
        </div>
        <div class="col-4 img-right">
            <img src="{% static 'img/parking.png' %}" alt="Planos de contratacao">
        </div>

        <div class="col-12 img-right">
            <button type="submit" class="btn btn-primary btn-lg">Contratar</button>
        </div>        

        <div class="col-8 row-space">
            <p>
                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Id of
                ficia eius iusto eos labore fuga similique reprehenderit! Ducim
                us voluptatum, quisquam facere cumque, quasi id doloremque repu
                diandae incidunt eum porro sint!
                Lorem ipsum dolor sit amet consectetur, adipisicing elit. Facil
                is, quo. Quibusdam repudiandae, at quasi odit sint incidunt ali
                quam eum veniam! Laudantium saepe hic ipsum nesciunt nam ex in 
                id odio.
            </p>
            <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad sint
                sit dolore exercitationem vero totam maiores ipsa cumque asperi
                ores quibusdam ipsam facere deserunt quos at nihil blanditiis h
                arum, debitis incidunt!
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere,
                praesentium? Harum accusantium cum aliquid dolores perspiciatis,
                minus laboriosam veritatis accusamus ut dolor quidem minima, et
                impedit natus repudiandae. Voluptatum, porro.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Optio b
                eatae nemo sit quae tempora dolorum debitis? Voluptate ea ipsa, 
                obcaecati atque quasi accusamus accusantium laboriosam? Optio mag
                nam ex eaque facere.
            </p>
        </div>

        <div class="col-4 img-right row-space">
            <img src="{% static 'img/parking.png' %}" alt="Planos de contratacao">            
        </div>

        <div class="col-12 img-right">
            <button type="submit" class="btn btn-primary btn-lg">Contratar</button>
        </div>  
    </div>
{% endblock main %}

website/templates/website/servicos.html
{% extends "website/base.html" %}
{% load static %}

{% block main %}
<div class="row row-space">
    <div class="col-12">
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Itaque rem 
        nostrum ea modi in ab dolorem, soluta cupiditate. Rerum, placeat sit.
         Adipisci, aperiam nam provident consequuntur minus mollitia nesciunt
          sint!
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Vero, dolor
         debitis accusantium architecto necessitatibus adipisci provident, re
         m nisi sint eaque reiciendis sapiente, ducimus officia atque ut. Eos
          delectus a minus.
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quibusdam fa
        cilis accusamus enim voluptatem rerum blanditiis eos dolor? Temporibus
         eius at, obcaecati sed, quis provident voluptatum tempore asperiores 
         reprehenderit nobis quae
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam dolor
        emque ipsam voluptatum dolorum vel quis, vero sint explicabo illo blan
        ditiis eius natus a eligendi quae porro, modi dignissimos sed suscipit?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sint ipsam r
        eprehenderit autem obcaecati, aut enim debitis magni magnam nostrum ab
         et nam. Aliquam consequatur consequuntur totam ullam in nisi providen
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitatione
        m quidem cum aspernatur quod deleniti similique quos, eligendi incidun
        t tempora laboriosam in delectus quaerat provident! Non corporis quod 
        illum aperiam eligendi!
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus aliqu
        am, porro pariatur at consequatur officiis mollitia doloribus odio, eo
        s a reprehenderit maxime, deleniti aspernatur perspiciatis! Eaque non 
        quam esse dolorem?
    </div>
    <div class="col-6 row-space">
        <img src="{% static 'img/logo.png' %}" alt="Servicos estacionamento 24 horas">
        <img src="{% static 'img/logo.png' %}" alt="Servicos estacionamento 24 horas">
    </div>
    <div class="col-6 row-space">
        <img src="{% static 'img/parking.png' %}" alt="Servicos estacionamento 24 horas">
        <img src="{% static 'img/parking.png' %}" alt="Servicos estacionamento 24 horas">
    </div>
</div>    
{% endblock main %}

website/templates/website/sobre.html
{% extends "website/base.html" %}
{% load static %}

{% block main %}
    <div class="row row-space">
        <h2>Sobre a nossa História</h2>
        <div class="col-12">
            <p>
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Magni animi cumque totam debitis tempore, vitae magnam maiores quasi unde odio. Doloremque voluptates natus nisi cupiditate saepe sequi earum itaque iure?
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa autem voluptatibus quidem atque velit sunt. Explicabo voluptas obcaecati possimus blanditiis consectetur! Sint eligendi a quasi! Ipsam recusandae facere aut reprehenderit.
            </p>
            <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio pariatur asperiores nulla dicta nostrum tempore distinctio, quae blanditiis temporibus soluta porro adipisci hicat aperiam natus, nemo reiciendis a ipsum!
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Rerum laborum porro, alias molestiae, repellat non vel magnam temporibus nostrum, mollitia voluptatem nam fugiat eligendi explicabo doloremque quasi vero laboriosam velit?        
            </p>
        </div>
        <div class="col-7">
            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur nam necessitatibus tempora deleniti officia tenetur vitae quasi velit incidunt, maiores repudiandae rerum eos consequatur cupiditate nobis doloremque ea laudantium voluptatum.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur perferendis, libero cupiditate ratione magnam ullam eos odit deserunt, perspiciatis eius totam doloremque eligendi voluptatibus dignissimos illum. Quam quibusdam enim architecto.
            </p>
            <p>
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolore harum incidunt porro magni quisquam ipsum, cumque sapiente obcaecati eum, reiciendis accusantium doloremque soluta debitis sunt aut ducimus cupiditate repellat! Laborum?
            </p>
        </div>
        <div class="col-5">
                <img src="{% static 'img/logo.png' %}" alt="Nossa historia">
                <img src="{% static 'img/parking.png' %}" alt="Nossa historia">
        </div>     
        
    </div>
{% endblock main %}