core/urls.py
from django.urls import path, include

from .views import (
    home,
    lista_pessoas,
    lista_veiculos,
    lista_movrotativos,
    lista_mensalistas,
    lista_movmensalistas,
    pessoa_novo,
    veiculo_novo,
    movrotativos_novo,
    mensalista_novo,
    movmensalista_novo,
    pessoa_update,
    veiculo_update,
    movrotativos_update,
    mensalista_update,
    movmensalista_update,
    pessoa_delete,
    veiculo_delete,
    movrotativos_delete,
    mensalista_delete,
    movmensalista_delete,
    logout_user,
    )


app_name = "core"
urlpatterns = [
    path("", home, name="core_home"),
    path("pessoas/", lista_pessoas, name="core_lista_pessoas"),
    path("pessoa-novo/", pessoa_novo, name="core_pessoa_novo"),
    path("pessoa-update/<int:id>/", pessoa_update, name="core_pessoa_update"),
    path("pessoa-delete/<int:id>/", pessoa_delete, name="core_pessoa_delete"),

    path("veiculos/", lista_veiculos, name="core_lista_veiculos"),
    path("veiculo-novo/", veiculo_novo, name="core_veiculo_novo"),
    path("veiculo-update/<int:id>/", veiculo_update, name="core_veiculo_update"),
    path("veiculo-delete/<int:id>/", veiculo_delete, name="core_veiculo_delete"),

    path("mov-rot/", lista_movrotativos, name="core_lista_movrotativos"),
    path("mov-rot-novo/", movrotativos_novo, name="core_movrotativos_novo"),
    path("mov-rot-update/<int:id>/", movrotativos_update,
         name="core_movrotativos_update"),
    path("mov-rot-delete/<int:id>/", movrotativos_delete,
         name="core_movrotativos_delete"),

    path("mensalistas/", lista_mensalistas, name="core_lista_mensalistas"),
    path("mensalista-novo/", mensalista_novo, name="core_mensalista_novo"),
    path("mensalista-update/<int:id>/", mensalista_update,
         name="core_mensalista_update"),
    path("mensalista-delete/<int:id>/", mensalista_delete,
         name="core_mensalista_delete"),

    path("mov-mensal/", lista_movmensalistas,
         name="core_lista_movmensalistas"),
    path("mov-mensal-novo/", movmensalista_novo,
         name="core_movmensalista_novo"),
    path("movmensal-update/<int:id>/", movmensalista_update,
         name="core_movmensalista_update"),
    path("mov-mensal-delete/<int:id>/", movmensalista_delete,
         name="core_movmensalista_delete"),

    path("logout/", logout_user, name="logout"),
]

estacionamento/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('website.urls')),
    path("sistema/", include("core.urls")),
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
]

core/models.py
from django.db import models
import math


class Pessoa(models.Model):
    nome = models.CharField(max_length=100)
    endereco = models.CharField(max_length=200)
    telefone = models.CharField(max_length=20)

    def __str__(self):
        return self.nome



class Marca(models.Model):
    nome = models.CharField(max_length=50)

    def __str__(self):
        return self.nome



class Veiculo(models.Model):
    marca = models.ForeignKey(Marca, on_delete=models.CASCADE)
    placa = models.CharField(max_length=7)
    proprietario = models.ForeignKey(Pessoa, on_delete=models.CASCADE)
    cor = models.CharField(max_length=15)
    observacoes = models.TextField()

    def __str__(self):
        return self.marca.nome + " - " + self.placa



class Parametros(models.Model):
    valor_hora = models.DecimalField(max_digits=5, decimal_places=2)
    valor_mensal = models.DecimalField(max_digits=6, decimal_places=2)

    def __str__(self):
        return "Parametros Gerais"



class MovRotativo(models.Model):
    checkin = models.DateTimeField(auto_now=False)
    checkout = models.DateTimeField(auto_now=False, null=True, blank=True)
    valor_hora = models.DecimalField(max_digits=5, decimal_places=2)
    veiculo = models.ForeignKey(Veiculo, on_delete=models.CASCADE)
    pago = models.BooleanField(default=False)


    def horas_total(self):
        return math.ceil((self.checkout - self.checkin).total_seconds() / 3600)


    def total(self):
        return self.valor_hora * self.horas_total()


    def __str__(self):
        return self.veiculo.placa



class Mensalista(models.Model):
    veiculo = models.ForeignKey(Veiculo, on_delete=models.CASCADE)
    inicio = models.DateField()
    valor_mes = models.DecimalField(max_digits=6, decimal_places=2)

    def __str__(self):
        return str(self.veiculo) + " - " + str(self.inicio)



class MovMensalista(models.Model):
    mensalista = models.ForeignKey(Mensalista, on_delete=models.CASCADE)
    dt_pgto = models.DateField()
    total = models.DecimalField(max_digits=6, decimal_places=2)


    def __str__(self):
        return str(self.mensalista) + " - " + str(self.total)

core/forms.py
from django.forms import ModelForm
from .models import Pessoa, Veiculo, MovRotativo, Mensalista, MovMensalista


class PessoaForm(ModelForm):
    class Meta:
        model = Pessoa
        fields = "__all__"


class VeiculoForm(ModelForm):
    class Meta:
        model = Veiculo
        fields = "__all__"


class MovRotativoForm(ModelForm):
    class Meta:
        model = MovRotativo
        fields = "__all__"


class MensalistaForm(ModelForm):
    class Meta:
        model = Mensalista
        fields = "__all__"


class MovMensalistaForm(ModelForm):
    class Meta:
        model = MovMensalista
        fields = "__all__"

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.urls import reverse
from .models import (
    Pessoa,
    Veiculo,
    MovRotativo,
    Mensalista,
    MovMensalista
    )

from .forms import (
    PessoaForm,
    VeiculoForm,
    MovRotativoForm,
    MensalistaForm,
    MovMensalistaForm
    )


def home(request):
    context = {"mensagem": "Seja bem vindo ao sistema de estacionamento!"}
    return render(request, "core/index.html", context)


@login_required
def lista_pessoas(request):
    pessoas = Pessoa.objects.all()
    form = PessoaForm()
    data = { "pessoas": pessoas, "form": form }
    return render(request, "core/lista_pessoas.html", data)


@login_required
def pessoa_novo(request):
    form = PessoaForm(request.POST or None)
    if form.is_valid():
        form.save()
    return redirect(reverse("core:core_lista_pessoas"))


@login_required
def pessoa_update(request, id):
    data = {}
    pessoa = Pessoa.objects.get(id=id)
    form = PessoaForm(request.POST or None, instance=pessoa)
    data["pessoa"] = pessoa
    data["form"] = form

    if request.method == "POST":
        if form.is_valid():
            form.save()
            return redirect(reverse("core:core_lista_pessoas"))
    else:
        return render(request, "core/update_pessoa.html", data)


@login_required
def pessoa_delete(request, id):
    pessoa = Pessoa.objects.get(id=id)
    if request.method == "POST":
        pessoa.delete()
        return redirect(reverse("core:core_lista_pessoas"))
    else:
        return render(request, "core/delete_confirm.html", {"obj": pessoa})


@login_required
def lista_veiculos(request):
    veiculos = Veiculo.objects.all()
    form = VeiculoForm()
    data = { "veiculos": veiculos, "form": form }
    return render(request, "core/lista_veiculos.html", data)


@login_required
def veiculo_novo(request):
    form = VeiculoForm(request.POST or None)
    if form.is_valid():
        form.save()
    return redirect(reverse("core:core_lista_veiculos"))


@login_required
def veiculo_update(request, id):
    data = {}
    veiculo = Veiculo.objects.get(id=id)
    form = VeiculoForm(request.POST or None, instance=veiculo)
    data["veiculo"] = veiculo
    data["form"] = form

    if request.method == "POST":
        if form.is_valid():
            form.save()
            return redirect(reverse("core:core_lista_veiculos"))
    else:
        return render(request, "core/update_veiculo.html", data)


@login_required
def veiculo_delete(request, id):
    veiculo = Veiculo.objects.get(id=id)
    if request.method == "POST":
        veiculo.delete()
        return redirect(reverse("core:core_lista_veiculos"))
    else:
        return render(request, "core/delete_confirm.html", {"obj": veiculo})


@login_required
def lista_movrotativos(request):
    mov_rot = MovRotativo.objects.all()
    form = MovRotativoForm()
    data = {"mov_rot": mov_rot, "form": form }
    return render(
        request, "core/lista_movrotativos.html", data)


@login_required
def movrotativos_novo(request):
    form = MovRotativoForm(request.POST or None)
    if form.is_valid():
        form.save()
    return redirect(reverse("core:core_lista_movrotativos"))


@login_required
def movrotativos_update(request, id):
    data = {}
    mov_rotativo = MovRotativo.objects.get(id=id)
    form = MovRotativoForm(request.POST or None, instance=mov_rotativo)
    data["mov_rotativo"] = mov_rotativo
    data["form"] = form

    if request.method == "POST":
        if form.is_valid():
            form.save()
            return redirect(reverse("core:core_lista_movrotativos"))
    else:
        return render(request, "core/update_movrotativos.html", data)


@login_required
def movrotativos_delete(request, id):
    mov_rotativo = MovRotativo.objects.get(id=id)
    if request.method == "POST":
        mov_rotativo.delete()
        return redirect(reverse("core:core_lista_movrotativos"))
    else:
        return render(request, "core/delete_confirm.html", {"obj": mov_rotativo})


@login_required
def lista_mensalistas(request):
    mensalistas = Mensalista.objects.all()
    form = MensalistaForm()
    data = { "mensalistas": mensalistas, "form": form }
    return render(
        request, "core/lista_mensalistas.html", data)


@login_required
def mensalista_novo(request):
    form = MensalistaForm(request.POST or None)
    if form.is_valid():
        form.save()
    return redirect(reverse("core:core_lista_mensalistas"))


@login_required
def mensalista_update(request, id):
    data = {}
    mensalista = Mensalista.objects.get(id=id)
    form = MensalistaForm(request.POST or None, instance=mensalista)
    data["mensalista"] = mensalista
    data["form"] = form

    if request.method == "POST":
        if form.is_valid():
            form.save()
            return redirect(reverse("core:core_lista_mensalistas"))
    else:
        return render(request, "core/update_mensalista.html", data)


@login_required
def mensalista_delete(request, id):
    mensalista = Mensalista.objects.get(id=id)
    if request.method == "POST":
        mensalista.delete()
        return redirect(reverse("core:core_lista_mensalistas"))
    else:
        return render(request, "core/delete_confirm.html", {"obj": mensalista})


@login_required
def lista_movmensalistas(request):
    mov_mensalistas = MovMensalista.objects.all()
    form = MovMensalistaForm()
    data = { "mov_mensalistas": mov_mensalistas, "form": form }
    return render(
        request, "core/lista_movmensalistas.html", data)


@login_required
def movmensalista_novo(request):
    form = MovMensalistaForm(request.POST or None)
    if form.is_valid():
        form.save()
    return redirect(reverse("core:core_lista_movmensalistas"))


@login_required
def movmensalista_update(request, id):
    data = {}
    mov_mensalista = MovMensalista.objects.get(id=id)
    form = MovMensalistaForm(request.POST or None, instance=mov_mensalista)
    data["mov_mensalista"] = mov_mensalista
    data["form"] = form

    if request.method == "POST":
        if form.is_valid():
            form.save()
            return redirect(reverse("core:core_lista_movmensalistas"))
    else:
        return render(request, "core/update_movmensalista.html", data)


@login_required
def movmensalista_delete(request, id):
    mov_mensalista = MovMensalista.objects.get(id=id)
    if request.method == "POST":
        mov_mensalista.delete()
        return redirect(reverse("core:core_lista_movmensalistas"))
    else:
        return render(request, "core/delete_confirm.html", {"obj": mov_mensalista})


def logout_user(request):
    logout(request)
    messages.success(request,("You have been logged out... Thanks for stopping by..."))
    return redirect("core:core_home")

core/templates/core/delete_confirm.html
{% extends "base.html" %}


{% block main %}

<div class="row">
    <div class="col">
        <h2>Tem certeza que deseja deletar {{ obj }}?</h2>

        <form method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Deletar</button>
        </form>
    </div>
</div>    

{% endblock main %}

core/templates/core/lista_mensalistas.html
{% extends "base.html" %}
{% load bootstrap %}

{% block menu %}
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'core:core_home' %}">Home</a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle active" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Servicos</a>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'core:core_lista_pessoas' %}">Pessoas</a></li>
                <li><a class="dropdown-item" href="{% url 'core:core_lista_veiculos' %}">Veiculos</a></li>
                <li><a class="dropdown-item active" href="{% url 'core:core_lista_mensalistas' %}">Mensalistas</a></li>            
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'core:core_lista_movrotativos' %}">Mov Rotativo</a></li>            
                <li><a class="dropdown-item" href="{% url 'core:core_lista_movmensalistas' %}">Mov Mensalistas</a></li>
            </ul>
        </li>
        {% if user.is_authenticated %}
            <li class="nav-item">                
                <a class="nav-link" href="{% url 'core:logout' %}">Logout</a>            
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Ola, {{ user }}</a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
        {% endif %}    
    </ul>
{% endblock menu %}

{% block main %}        
    <div class="row">
        <div class="col-sm-6">
            <h2>Cadastro de Mensalistas</h2>
            <form action="{% url 'core:core_mensalista_novo' %}" method="POST">
                {% csrf_token %}
        
                {{ form|bootstrap }}
        
                <button type="submit" class="btn btn-primary">Cadastrar</button>
            </form>
        </div>
    
        <div class="col-sm-6">
            <h2>Mensalistas cadastrados</h2>
            <table class="table caption-top">
                <caption>List of monthly parking payers</caption>
                <thead class="table-dark">
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Veiculo</th>
                        <th scope="col">Inicio</th>
                        <th scope="col">Valor</th>
                    </tr>
                </thead>
                <tbody>
                    {% for mensalista in mensalistas %}
                        <tr>
                            <th scope="row">{{ mensalista.id }}</th>
                            <td>{{ mensalista.veiculo }}</td>
                            <td>{{ mensalista.inicio }}</td>
                            <td>R$ {{ mensalista.valor_mes }}</td>
                        </tr>    
                    {% endfor %}                                  
                </tbody>
            </table>
        </div>    
    </div>       

{% endblock main %}

core/templates/core/lista_movmensalistas.html
{% extends "base.html" %}
{% load bootstrap %}

{% block menu %}
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'core:core_home' %}">Home</a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle active" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Servicos</a>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'core:core_lista_pessoas' %}">Pessoas</a></li>
                <li><a class="dropdown-item" href="{% url 'core:core_lista_veiculos' %}">Veiculos</a></li>
                <li><a class="dropdown-item" href="{% url 'core:core_lista_mensalistas' %}">Mensalistas</a></li>            
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'core:core_lista_movrotativos' %}">Mov Rotativo</a></li>            
                <li><a class="dropdown-item active" href="{% url 'core:core_lista_movmensalistas' %}">Mov Mensalistas</a></li>
            </ul>
        </li>
        {% if user.is_authenticated %}
            <li class="nav-item">                
                <a class="nav-link" href="{% url 'core:logout' %}">Logout</a>            
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Ola, {{ user }}</a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
        {% endif %}    
    </ul>
{% endblock menu %}

{% block main %}    
    <div class="row">
        <div class="col-sm-6">
            <h2>Cadastro de Movimentos Mensalistas</h2>
            <form action="{% url 'core:core_movmensalista_novo' %}" method="POST">
                {% csrf_token %}
        
                {{ form|bootstrap }}
        
                <button type="submit" class="btn btn-primary">Cadastrar</button>
            </form>
        </div>

        <div class="col-sm-6">
            <h2>Mov Mensalistas Cadastrados</h2>
            <table class="table caption-top">
                <caption>List of monthly parking payers</caption>
                <thead class="table-dark">
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Mensalista</th>
                        <th scope="col">Data Pagto</th>
                        <th scope="col">R$ Total</th>
                                             
                    </tr>
                </thead>
                <tbody>
                    {% for mov in mov_mensalistas %}
                        <tr>
                            <th scope="row">{{ mov.id }}</th>
                            <td>{{ mov.mensalista }}</td>
                            <td>{{ mov.dt_pgto }}</td>                          
                            <td>R$ {{ mov.total }}</td>
                        </tr>    
                    {% endfor %}                                  
                </tbody>
            </table>
        </div>        
    </div>
{% endblock main %}

core/templates/core/lista_movrotativos.html
{% extends "base.html" %}
{% load bootstrap %}

{% block menu %}
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'core:core_home' %}">Home</a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle active" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Servicos</a>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'core:core_lista_pessoas' %}">Pessoas</a></li>
                <li><a class="dropdown-item" href="{% url 'core:core_lista_veiculos' %}">Veiculos</a></li>
                <li><a class="dropdown-item" href="{% url 'core:core_lista_mensalistas' %}">Mensalistas</a></li>            
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item active" href="{% url 'core:core_lista_movrotativos' %}">Mov Rotativo</a></li>            
                <li><a class="dropdown-item" href="{% url 'core:core_lista_movmensalistas' %}">Mov Mensalistas</a></li>
            </ul>
        </li>
        {% if user.is_authenticated %}
            <li class="nav-item">                
                <a class="nav-link" href="{% url 'core:logout' %}">Logout</a>            
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Ola, {{ user }}</a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
        {% endif %}    
    </ul>
{% endblock menu %}

{% block main %}
    <div class="row">
        <div class="col-sm-6">
            <h2>Cadastro Rotativos</h2>
            <form action="{% url 'core:core_movrotativos_novo' %}" method="POST">
                {% csrf_token %}
        
                {{ form|bootstrap }}
        
                <button type="submit" class="btn btn-primary">Cadastrar</button>
            </form>
        </div>
        
        <div class="col-sm-6">
            <h2>Rotativos cadastrados</h2>
            <table class="table caption-top">
                <caption>List of rotary parking</caption>
                <thead class="table-dark">
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Checkin</th>
                        <th scope="col">Checkout</th>
                        <th scope="col">R$ Hora</th>
                        <th scope="col">Horas</th>
                        <th scope="col">Total</th>
                    </tr>
                </thead>
                <tbody>
                    {% for mov in mov_rot %}
                        <tr>
                            <th scope="row">{{ mov.id }}</th>
                            <td>{{ mov.checkin }}</td>
                            <td>{{ mov.checkout }}</td>
                            <td>{{ mov.valor_hora }}</td>
                            <td>{{ mov.horas_total }}</td>
                            <td>R$ {{ mov.total }}</td>
                        </tr>    
                    {% endfor %}                                  
                </tbody>
            </table>
        </div>
    </div>

{% endblock main %}

core/templates/core/lista_pessoas.html
{% extends "base.html" %}
{% load bootstrap %}

{% block menu %}
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'core:core_home' %}">Home</a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle active" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Servicos</a>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item active" href="{% url 'core:core_lista_pessoas' %}">Pessoas</a></li>
                <li><a class="dropdown-item" href="{% url 'core:core_lista_veiculos' %}">Veiculos</a></li>
                <li><a class="dropdown-item" href="{% url 'core:core_lista_mensalistas' %}">Mensalistas</a></li>            
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'core:core_lista_movrotativos' %}">Mov Rotativo</a></li>            
                <li><a class="dropdown-item" href="{% url 'core:core_lista_movmensalistas' %}">Mov Mensalistas</a></li>
            </ul>
        </li>
        {% if user.is_authenticated %}
            <li class="nav-item">                
                <a class="nav-link" href="{% url 'core:logout' %}">Logout</a>            
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Ola, {{ user }}</a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
        {% endif %}    
    </ul>
{% endblock menu %}

{% block main %}
    
    <div class=row>        
        <div class="col-sm-6">
            <h2>Formulario de cadastro</h2>            
            <form action="{% url 'core:core_pessoa_novo' %}" method="POST">
                {% csrf_token %}
        
                {{ form|bootstrap }}
        
                <button type="submit" class="btn btn-primary">Cadastrar</button>    
            </form>
        </div>

        <div class="col-sm-6">
            <h2>Pessoas cadastradas</h2>
            <table class="table caption-top">
                <caption>List of people</caption>
                <thead class="table-dark">
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Nome</th>
                        <th scope="col">Endereco</th>
                        <th scope="col">Telefone</th>
                    </tr>
                </thead>
                <tbody>
                    {% for pessoa in pessoas %}
                        <tr>
                            <th scope="row">{{ pessoa.id }}</th>
                            <td>{{ pessoa.nome }}</td>
                            <td>{{ pessoa.endereco }}</td>
                            <td>{{ pessoa.telefone }}</td>
                        </tr>    
                    {% endfor %}                                  
                </tbody>
            </table>
        </div>        
    </div>    

{% endblock main %}

core/templates/core/lista_veiculos.html
{% extends "base.html" %}
{% load bootstrap %}

{% block menu %}
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'core:core_home' %}">Home</a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle active" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Servicos</a>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'core:core_lista_pessoas' %}">Pessoas</a></li>
                <li><a class="dropdown-item active" href="{% url 'core:core_lista_veiculos' %}">Veiculos</a></li>
                <li><a class="dropdown-item" href="{% url 'core:core_lista_mensalistas' %}">Mensalistas</a></li>            
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'core:core_lista_movrotativos' %}">Mov Rotativo</a></li>            
                <li><a class="dropdown-item" href="{% url 'core:core_lista_movmensalistas' %}">Mov Mensalistas</a></li>
            </ul>
        </li>
        {% if user.is_authenticated %}
            <li class="nav-item">                
                <a class="nav-link" href="{% url 'core:logout' %}">Logout</a>            
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Ola, {{ user }}</a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
        {% endif %}    
    </ul>
{% endblock menu %}

{% block main %}
    <div class="row">                
        <div class="col-sm-6">
            <h2>Cadastro de veículos</h2>
            <form action="{% url 'core:core_veiculo_novo' %}" method="POST">
            {% csrf_token %}
    
            {{ form|bootstrap }}
    
            <button type="submit" class="btn btn-primary">Cadastrar</button>
            </form>
        </div>
        <div class="col-sm-6">
            <h2>Veiculos cadastrados</h2>
            <table class="table caption-top">
                <caption>List of vehicles</caption>
                <thead class="table-dark">
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Marca</th>
                        <th scope="col">Placa</th>
                        <th scope="col">Proprietario</th>
                    </tr>
                </thead>
                <tbody>
                    {% for veiculo in veiculos %}
                        <tr>
                            <th scope="row">{{ veiculo.id }}</th>
                            <td>{{ veiculo.marca }}</td>
                            <td>{{ veiculo.placa }}</td>
                            <td>{{ veiculo.proprietario }}</td>
                        </tr>    
                    {% endfor %}                                  
                </tbody>
            </table>
        </div>
    </div>

{% endblock main %}

core/templates/core/update_mensalista.html
{% extends "base.html" %}
{% load bootstrap %}

{% block main %}

    <div class="row">
        <div class="col">
            <h2>Updating Mensalistas: {{ mensalista }}</h2>

            <form action="{% url 'core:core_mensalista_update' mensalista.id %}"
                            method="POST">
                {% csrf_token %}

                {{ form|bootstrap }}

                <button type="submit" class="btn btn-primary">Salvar</button>
                <a href="{% url 'core:core_mensalista_delete' mensalista.id %}" class="btn btn-danger">Deletar</a>
            </form>
        </div>
    </div>    

{% endblock main %}

core/templates/core/update_movmensalista.html
{% extends "base.html" %}
{% load bootstrap %}

{% block main %}

    <div class="row">
        <div class="col">
            <h2>Updating Movimentos Mensalista {{ mov_mensalista }}</h2>

            <form action="{% url 'core:core_movmensalista_update' mov_mensalista.id %}"
                            method="POST">
                {% csrf_token %}

                {{ form|bootstrap }}

                <button type="submit" class="btn btn-primary">Salvar</button>
                <a href="{% url 'core:core_movmensalista_delete'  mov_mensalista.id%}" class="btn btn-danger">Deletar</a>
            </form>
        </div>
    </div>

{% endblock main %}